name: 'Setup environment'

inputs:
  aws-region:
    description: 'The AWS region'
    default: 'us-east-1'
  aws-access-key:
    description: 'The AWS access key'
    required: true
  aws-secret-key:
    description: 'The AWS secret key'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        rm awscliv2.zip
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        aws-access-key-id: ${{ inputs.aws-access-key }}
        aws-secret-access-key: ${{ inputs.aws-secret-key }}
