name: 'Setup environment'

inputs:
  aws-region:
    description: 'The AWS region'
    default: 'us-east-1'
  aws-access-key:
    description: 'The AWS access key'
    required: true
  aws-secret-key:
    description: 'The AWS secret key'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Display test
      run: echo "${{ inputs.aws-region }} --- ${{ inputs.aws-access-key }} --- ${{ inputs.aws-secret-key }}"
      shell: bash
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key }}
        aws-secret-access-key: ${{ inputs.aws-secret-key }}
        aws-region: ${{ inputs.aws-region }}
