name: Deploy to Amazon ECS

on: 
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      task-definition:
        required: true
        type: string
      output-ci-job:
        required: true
        type: string

jobs:
  deploy_task_ECS:
    name: deploy_task_ECS
    runs-on: ubuntu-latest
    environment: Develop

    steps:
    - name: setup environment
      uses: ./.github/actions/demo-composite-action
      with:
        aws-region: ${{ inputs.aws-region }}

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ inputs.task-definition }}
        container-name: ${{ vars.CONTAINER_NAME }}
        image: ${{ inputs.output-ci-job }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ vars.ECS_SERVICE }}
        cluster: ${{ vars.ECS_CLUSTER }}
        wait-for-service-stability: true
