name: Build and push image to ECR

on: 
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string

jobs:
  deploy_image_ECR:
    name: deploy_image_ECR
    runs-on: ubuntu-latest
    environment: Develop

    outputs:
      build-image: ${{ steps.build-image.outputs.image }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Display the path
      shell: bash
      run: ls -la ${{ github.workspace }}
    
    - name: setup environment
      uses: ./.github/actions/setup.yml
      with:
        aws-region: ${{ inputs.aws-region }}

    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v1

    # - name: Build, tag, and push image to Amazon ECR
    #   id: build-image
    #   env:
    #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #     IMAGE_TAG: ${{ github.sha }}
    #   run: |
    #     docker build -t $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:$IMAGE_TAG .
    #     docker push $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:$IMAGE_TAG
    #     echo "image=$ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_OUTPUT
