name: Build and push image to ECR

on: 
  workflow_call:

jobs:
  deploy_image_ECR:
    name: deploy_image_ECR
    runs-on: ubuntu-latest
    environment: Develop

    outputs:
      build-image: ${{ steps.build-image.outputs.image }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: setup environment
      uses: ./.github/actions/demo-composite-action
      with:
        aws-region: ${{ vars.AWS_REGION }}
        aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:$IMAGE_TAG .
        docker push $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_OUTPUT
    
    - name: test
      run: echo "build-image output => $GITHUB_OUTPUT"
      shell: bash
