name: Workflow to deploy to Amazon ECS

on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'releases/**'
    paths-ignore:
      - '.github/**'

permissions:
  contents: read

jobs:
  ci_workflow:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  cd_workflow:
    needs: ci_workflow
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    with:
      output-ci-job: ${{ needs.ci_workflow.outputs.image }}
