name: Workflow to deploy to Amazon ECS

on: 
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci_workflow:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  cd_workflow:
    needs: ci_workflow
    uses: ./.github/workflows/cd.yml
    with:
      output-ci-job: ${{ needs.ci_workflow.outputs.build-image }}
